project:
  title: CASCADES
  description: Production de trames narratives pour le projet CASCAES

tasks:
  extract: False
  indicators: True

region:
  name: SouthQC
  method: bbox
  buffer: 1.5
  bbox:
    lon_bnds: [-83, -55.5]
    lat_bnds: [43, 54]

spei:
  cal_period: ['1991', '2020']
  # https://www.eea.europa.eu/data-and-maps/daviz/global-average-air-temperature-anomalies-6#tab-dashboard-01
  # Real 1991-2020 = +0.80°C
#  warming_levels: [0.8, 1.5, 2, 3, 4]
  warming_levels: [0.8]
  windows: [3, 6, 9]
  good_months: [5, 6, 7, 8, 9, 10, 11]

dask:
  n_workers: 10
  threads_per_worker: 3
  memory_limit: 20GB

chunks:
  extract:
    time: 1000
    lat: -1
    lon: -1
  indicators:
    time: 100
    lat: -1
    lon: -1
