realm: land
indicators:
  discharge_mean_mon:
    base: discharge_stats
    parameters:
      op: mean
      freq: MS
  discharge_mean_yr:
    base: discharge_stats
    parameters:
      op: mean
      freq: AS-DEC
  7q2:
    base: freq_analysis
    parameters:
      mode: min
      window: 7
      t: 2
      dist: lognorm
      indexer:
        month: [5, 6, 7, 8, 9, 10, 11]
